-- 직무의 개수 
SELECT COUNT(DISTINCT JOB)
FROM EMP;


-- 각 부서의 소속 인원을 구하자 
SELECT DEPTNO, COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO 

-- 각 부서별 총 급여액 출력 
SELECT DEPTNO , TO_CHAR(SUM(SAL), 'L999,999.999')
FROM EMP 
GROUP BY DEPTNO 
ORDER BY DEPTNO;

-- 각 부서별 급여 평균
SELECT DEPTNO, ROUND(AVG(SAL), 2)
FROM EMP 
GROUP BY DEPTNO 
ORDER BY DEPTNO;

-- 각 부서별 최고 금액과 최소금액 출력 
SELECT DEPTNO, MIN(SAL), MAX(SAL)
FROM EMP 
GROUP BY DEPTNO 
ORDER BY DEPTNO;